#!/usr/bin/php
<?php
$par  =  "p:";
$par  .=  "d:";
$options = getopt($par);
//print_r( $options);
//$data = trim($options["d"]);
$data=($options["d"]);

$info = <<<EOD

archeiogiainsertstinvassi

    INFO: data for mongodb
    OPTIONS:
        -d data

EOD;
if(!$options['d'] ){
        echo $info;
        die;
}


$dataArray = json_decode($data,true);

$m = new MongoClient();
$db = $m->diyiot_sensorsData;
$sensor_coll = $db->$dataArray['devID'];
// create a unique index on timestamp
//$sensor_coll->ensureIndex(array('timestamp' => 1));
$sensor_rec = array( "data" => $dataArray['data'], "when" => $dataArray['when']);       
$sensor_coll->insert($sensor_rec);



