#!/usr/bin/php
<?php

$par  =  "p:";
$par  .=  "d:";
$options = getopt($par);
$data = trim($options["d"]);

$info = <<<EOD

archeiogiainsertstinvassi

    INFO: data for mongodb
    OPTIONS:
        -d data

EOD;
if(!$options['d'] ){
        echo $info;
        die;
}


// edo echete ta data 
// opos ta stilate apo to mongodb.php
// prepei nata valete stin mongo
echo $data;


